routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('tvs/{id}/download', 'Admin\TVController@download')->name('tvs.download');
    Route::resource('tvs', 'Admin\TVController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::resource('programs', 'Admin\ProgramController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin,tv_user'])->group(function () {
    Route::get('ads/{id}/download', 'Admin\AdController@download')->name('ads.download');
    Route::resource('ads', 'Admin\AdController');
    Route::resource('mediaStreams', 'Admin\MediaStreamController');
    Route::resource('streamTargets', 'Admin\StreamTargetController');
});

app/Ad.php
<?php

namespace App;

use Eloquent as Model;
use Auth;
use Illuminate\Database\Eloquent\Builder;

class Ad extends Model
{

    public $table = 'ads';

    public $fillable = [
        'name',
        'file',
        'tv_id',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'file' => 'mimetypes:video/quicktime,video/mp4,video/x-flv,video/avi,video/mpeg|max:500000',
    ];

    protected static function boot()
    {
        parent::boot();
        
        static::addGlobalScope('owned', function (Builder $builder) {
            if (Auth::check() && !empty(Auth::user()->tv_id)) {
                $builder->where('ads.tv_id', Auth::user()->tv_id);
            }
        });

        static::saving(function ($instance){
            if (Auth::check() && !empty(Auth::user()->tv_id)) {
                $instance->tv_id = Auth::user()->tv_id;
            }
        });
    }

    public function tv()
    {
        return $this->belongsTo('App\TV');
    }
}

app/Http/Controllers/Admin/AdController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreateAdRequest;
use App\Http\Requests\UpdateAdRequest;
use App\Repositories\AdRepository;
use App\Http\Controllers\AppBaseController;
use Storage;
use Request;
use Flash;
use Response;

class AdController extends AppBaseController
{
    /** @var  AdRepository */
    private $adRepository;

    public function __construct(AdRepository $adRepo)
    {
        $this->adRepository = $adRepo;
    }

    /**
     * Display a listing of the Ad.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $ads = $this->adRepository->allQuery()->with('tv')->paginate(10);

        return view('admin.ads.index')
            ->with('ads', $ads);
    }

    /**
     * Show the form for creating a new Ad.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.ads.create');
    }

    /**
     * Store a newly created Ad in storage.
     *
     * @param CreateAdRequest $request
     *
     * @return Response
     */
    public function store(CreateAdRequest $request)
    {
        $input = $request->all();
        $ad = $this->adRepository->create($input);
        if ($request->hasFile('file')) {
            $filename = $request->file('file')->getClientOriginalName();
            $ad->file = $request->file('file')->storeAs("ads/{$ad->id}/file", $filename, 'local');
            $ad->save();
        }
        Flash::success('Ad saved successfully.');
        return redirect(route('admin.ads.index'));
    }

    /**
     * Display the specified Ad.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $ad = $this->adRepository->find($id);

        if (empty($ad)) {
            Flash::error('Ad not found');

            return redirect(route('admin.ads.index'));
        }

        return view('admin.ads.show')->with('ad', $ad);
    }

    /**
     * Show the form for editing the specified Ad.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $ad = $this->adRepository->find($id);

        if (empty($ad)) {
            Flash::error('Ad not found');

            return redirect(route('admin.ads.index'));
        }

        return view('admin.ads.edit')->with('ad', $ad);
    }

    /**
     * Update the specified Ad in storage.
     *
     * @param int $id
     * @param UpdateAdRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateAdRequest $request)
    {
        $ad = $this->adRepository->find($id);
        if (empty($ad)) {
            Flash::error('Ad not found');
            return redirect(route('admin.ads.index'));
        }

        $input = $request->all();
        if ($request->hasFile('file')) {
            $filename = $request->file('file')->getClientOriginalName();
            $input['file'] = $request->file('file')->storeAs("ads/{$id}/file", $filename, 'local');
        }
        $ad = $this->adRepository->update($input, $id);

        Flash::success('Ad updated successfully.');

        return redirect(route('admin.ads.index'));
    }

    /**
     * Remove the specified Ad from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $ad = $this->adRepository->find($id);

        if (empty($ad)) {
            Flash::error('Ad not found');

            return redirect(route('admin.ads.index'));
        }

        $this->adRepository->delete($id);

        Flash::success('Ad deleted successfully.');

        return redirect(route('admin.ads.index'));
    }

    public function download($id)
    {   
        $ad = $this->adRepository->find($id);
        if (empty($ad)) {
            return response(null, 404);
        }
        $size = Storage::size($ad->file);
        $type = Storage::mimeType($ad->file);
        $path = Storage::disk('local')->path($ad->file);
        $name = basename($path);
        return Response::streamed($type, $size, $name, function($offset, $length) use ($path) {
            $stream = \GuzzleHttp\Psr7\stream_for(fopen($path, 'r'));
            $stream->seek($offset);
            while (!$stream->eof()) {
                echo $stream->read($length);
            }
            $stream->close();
        });
    }
}

resources/views/admin/ads/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ad
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.ads.store', 'files' => true]) !!}

                        @include('admin.ads.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/ads/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Ad
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($ad, ['route' => ['admin.ads.update', $ad->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.ads.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/ads/fields.blade.php
<!-- Tv Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tv_id', 'TV:') !!}
    {!! Form::select('tv_id', \App\TV::pluck('name','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>

<!-- Tv Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tv_id', 'TV:') !!}
    {!! Form::select('tv_id', \App\TV::pluck('name','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['required' => true, 'class' => 'form-control']) !!}
</div>

<div class="clearfix"></div>

<!-- File Field -->
<div class="form-group col-sm-3">
    {!! Form::label('file', 'File:') !!}
    {!! Form::file('file', ['class' => 'form-control']) !!}
</div>

@if (!empty($ad))
<div class="clearfix"></div>
<div class="form-group col-sm-6">
    <video width="320" height="240" controls>
        <source src="{{ route('admin.ads.download', ['id' => $ad->id]) }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>  
</div>
<div class="clearfix"></div>
@endif

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.ads.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/ads/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Ads</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('admin.ads.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.ads.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $ads])

        </div>
    </div>
@endsection

resources/views/admin/ads/table.blade.php
<div class="table-responsive">
    <table class="table" id="ads-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>TV</th>
                <th>File</th>
                <th>Created At</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($ads as $ad)
            <tr>
                <td>{!! $ad->name !!}</td>
                <td>{!! $ad->tv->name !!}</td>
                <td>{!! $ad->file !!}</td>
                <td>{!! $ad->created_at !!}</td>
                <td>
                    {!! Form::open(['route' => ['admin.ads.destroy', $ad->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('admin.ads.edit', [$ad->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>