routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('tvs/{id}/download', 'Admin\TVController@download')->name('tvs.download');
    Route::resource('tvs', 'Admin\TVController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::resource('programs', 'Admin\ProgramController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin,tv_user'])->group(function () {
    Route::get('ads/{id}/download', 'Admin\AdController@download')->name('ads.download');
    Route::resource('ads', 'Admin\AdController');
    Route::resource('mediaStreams', 'Admin\MediaStreamController');
    Route::resource('streamTargets', 'Admin\StreamTargetController');
});

app/StreamTarget.php
<?php

namespace App;

use Eloquent as Model;
use Auth;
use Illuminate\Database\Eloquent\Builder;

class StreamTarget extends Model
{

    public $table = 'stream_targets';

    public $fillable = [
        'rtmp_target',
        'start',
        'end',
        'ffmpeg_args_0',
        'ffmpeg_args_1',
        'options',
        'program_id',
        'ad_id',
        'media_stream_id'
    ];

    protected $dates = [
        'start',
        'end',
    ];

    protected $with = [
        'ad',
        'program',
        'media_stream',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'rtmp_target' => 'required|url',
        'program_id' => 'required',
        'ad_id' => 'required',
        'ffmpeg_args_0' => 'regex:/.+{ad_file}.+{rtmp_target}/',
        'ffmpeg_args_1' => 'regex:/.+{rtmp_source}.+{rtmp_target}/',
        'options' => 'json',
        'start' => 'date',
        'end' => 'date|after:start',
    ];

    public function program()
    {
        return $this->belongsTo('App\Program');
    }

    public function media_stream()
    {
        return $this->belongsTo('App\MediaStream');
    }

    public function ad()
    {
        return $this->belongsTo('App\Ad');
    }

    protected static function boot()
    {
        parent::boot();
        
        static::addGlobalScope('owned', function (Builder $builder) {
            if (Auth::check() && !empty(Auth::user()->tv_id)) {
                $builder
                    ->select('stream_targets.*')
                    ->join('programs', 'stream_targets.program_id', 'programs.id')
                    ->where('programs.tv_id', Auth::user()->tv_id);
            }
        });
    }
}

app/Http/Controllers/Admin/StreamTargetController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreateStreamTargetRequest;
use App\Http\Requests\UpdateStreamTargetRequest;
use App\Repositories\StreamTargetRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use Auth;
use App\MediaStream;
use App\Program;
use App\Ad;

class StreamTargetController extends AppBaseController
{
    /** @var  StreamTargetRepository */
    private $streamTargetRepository;

    public function __construct(StreamTargetRepository $streamTargetRepo)
    {
        $this->streamTargetRepository = $streamTargetRepo;
    }

    /**
     * Validate ownership of referenced models
     */
    public function validateReference($input)
    {
        if (Auth::check() && !empty(Auth::user()->tv_id)) {
            if (array_key_exists('program_id', $input)) {
                $count = Program::where('programs.tv_id', Auth::user()->tv_id)
                    ->where('programs.id', $input['program_id'])
                    ->count();
                if ($count <= 0) return 'Program not found';
            }
            if (array_key_exists('ad_id', $input)) {
                $count = Ad::where('ads.tv_id', Auth::user()->tv_id)
                    ->where('ads.id', $input['ad_id'])
                    ->count();
                if ($count <= 0) return 'Ad not found';
            }
            if (array_key_exists('media_stream_id', $input)) {
                $count = MediaStream::where('media_streams.tv_id', Auth::user()->tv_id)
                    ->where('media_streams.id', $input['media_stream_id'])
                    ->count();                
                if ($count <= 0) return 'Media Stream not found';
            }            
        }
        return null;
    }

    /**
     * Display a listing of the StreamTarget.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $streamTargets = $this->streamTargetRepository->paginate(10);

        return view('admin.stream_targets.index')
            ->with('streamTargets', $streamTargets);
    }

    /**
     * Show the form for creating a new StreamTarget.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.stream_targets.create');
    }

    /**
     * Store a newly created StreamTarget in storage.
     *
     * @param CreateStreamTargetRequest $request
     *
     * @return Response
     */
    public function store(CreateStreamTargetRequest $request)
    {
        $input = $request->all();
        $error = $this->validateReference($input);
        if (!empty($error)) {
            Flash::error($error);
            return redirect()->back()->withInput();
        }
        $streamTarget = $this->streamTargetRepository->create($input);
        Flash::success('Stream Target saved successfully.');
        return redirect(route('admin.streamTargets.index'));
    }

    /**
     * Display the specified StreamTarget.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $streamTarget = $this->streamTargetRepository->find($id);
        if (empty($streamTarget)) {
            Flash::error('Stream Target not found');
            return redirect(route('admin.streamTargets.index'));
        }
        return view('admin.stream_targets.show')->with('streamTarget', $streamTarget);
    }

    /**
     * Show the form for editing the specified StreamTarget.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $streamTarget = $this->streamTargetRepository->find($id);
        if (empty($streamTarget)) {
            Flash::error('Stream Target not found');
            return redirect(route('admin.streamTargets.index'));
        }
        return view('admin.stream_targets.edit')->with('streamTarget', $streamTarget);
    }

    /**
     * Update the specified StreamTarget in storage.
     *
     * @param int $id
     * @param UpdateStreamTargetRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateStreamTargetRequest $request)
    {
        $streamTarget = $this->streamTargetRepository->find($id);
        if (empty($streamTarget)) {
            Flash::error('Stream Target not found');
            return redirect(route('admin.streamTargets.index'));
        }

        $input = $request->all();
        $error = $this->validateReference($input);
        if (!empty($error)) {
            Flash::error($error);
            return redirect()->back()->withInput();
        }
        if ($request->hasFile('logo_mask')) {
            $logo_mask_file = $request->file('logo_mask')->getClientOriginalName();
            $input['logo_mask'] = $request->file('logo_mask')->storeAs("stream_targets/{$streamTarget->id}/logo_mask", $logo_mask_file, 'local');
        }
        if ($request->hasFile('logo_masked')) {
            $logo_masked_file = $request->file('logo_masked')->getClientOriginalName();
            $input['logo_masked'] = $request->file('logo_masked')->storeAs("stream_targets/{$streamTarget->id}/logo_masked", $logo_masked_file, 'local');
        }
        $streamTarget = $this->streamTargetRepository->update($input, $id);

        Flash::success('Stream Target updated successfully.');
        return redirect(route('admin.streamTargets.index'));
    }

    /**
     * Remove the specified StreamTarget from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $streamTarget = $this->streamTargetRepository->find($id);

        if (empty($streamTarget)) {
            Flash::error('Stream Target not found');

            return redirect(route('admin.streamTargets.index'));
        }

        $this->streamTargetRepository->delete($id);

        Flash::success('Stream Target deleted successfully.');

        return redirect(route('admin.streamTargets.index'));
    }

}

resources/views/admin/stream_targets/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Stream Target
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.streamTargets.store']) !!}

                        @include('admin.stream_targets.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/stream_targets/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Stream Target
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($streamTarget, ['route' => ['admin.streamTargets.update', $streamTarget->id], 'method' => 'patch']) !!}

                        @include('admin.stream_targets.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/stream_targets/fields.blade.php
<!-- RTMP Target Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('rtmp_target', 'RTMP Target:') !!}
    {!! Form::textarea('rtmp_target', null, ['class' => 'form-control', 'rows' => 2]) !!}
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('ffmpeg_args_0', 'FFMPEG args 0:') !!}
    {!! Form::text('ffmpeg_args_0', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('ffmpeg_args_1', 'FFMPEG args 1:') !!}
    {!! Form::text('ffmpeg_args_1', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('options', 'Options:') !!}
    {!! Form::textarea('options', null, ['class' => 'form-control', 'rows' => 2]) !!}
</div>

<!-- Start Field -->
<div class="form-group col-sm-6">
    {!! Form::label('start', 'Start:') !!}
    {!! Form::text('start', null, ['class' => 'form-control datetimepicker']) !!}
</div>

<!-- End Field -->
<div class="form-group col-sm-6">
    {!! Form::label('end', 'End:') !!}
    {!! Form::text('end', null, ['class' => 'form-control datetimepicker']) !!}
</div>

<!-- Program Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('program_id', 'Program:') !!}
    {!! Form::select('program_id', \App\Program::all()->pluck('desc','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>

<!-- Ad Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('ad_id', 'Ad:') !!}
    {!! Form::select('ad_id', \App\Ad::pluck('name','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>

<!-- Media Stream Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('media_stream_id', 'Media Stream:') !!}
    {!! Form::select('media_stream_id', \App\MediaStream::pluck('name','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>


<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.streamTargets.index') !!}" class="btn btn-default">Cancel</a>
</div>

@section('scripts')
<script type="text/javascript">
$('.datetimepicker').datetimepicker({
    format: 'YYYY-MM-DD HH:mm:ss',
    useCurrent: false
})
</script>
@endsection

resources/views/admin/stream_targets/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Stream Targets</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('admin.streamTargets.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.stream_targets.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $streamTargets])

        </div>
    </div>
@endsection

resources/views/admin/stream_targets/table.blade.php
<div class="table-responsive">
    <table class="table" id="streamTargets-table">
        <thead>
            <tr>
            <th>TV</th>
            <th>Program</th>
            <th>Ad</th>
            <th>Media Stream</th>
            <th>Start</th>
            <th>End</th>        
            <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($streamTargets as $streamTarget)
            <tr>
                <td>{!! $streamTarget->program->tv->name !!}</td>
                <td>{!! $streamTarget->program->name !!}</td>
                <td>{!! $streamTarget->ad->name !!}</td>
                <td>{!! $streamTarget->media_stream->name !!}</td>
                <td>{!! $streamTarget->start !!}</td>
                <td>{!! $streamTarget->end !!}</td>
                <td>
                    {!! Form::open(['route' => ['admin.streamTargets.destroy', $streamTarget->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('admin.streamTargets.edit', [$streamTarget->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>