routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('tvs/{id}/download', 'Admin\TVController@download')->name('tvs.download');
    Route::resource('tvs', 'Admin\TVController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin'])->group(function () {
    Route::resource('users', 'Admin\UserController');
    Route::resource('programs', 'Admin\ProgramController');
});

Route::prefix('admin')->name('admin.')->middleware(['auth', 'role:admin,tv_admin,tv_user'])->group(function () {
    Route::get('ads/{id}/download', 'Admin\AdController@download')->name('ads.download');
    Route::resource('ads', 'Admin\AdController');
    Route::resource('mediaStreams', 'Admin\MediaStreamController');
    Route::resource('streamTargets', 'Admin\StreamTargetController');
});

app/MediaStream.php
<?php

namespace App;

use Eloquent as Model;
use Auth;
use Illuminate\Database\Eloquent\Builder;

class MediaStream extends Model
{

    public $table = 'media_streams';

    public $fillable = [
        'name',
        'tv_id',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required'
    ];

    protected static function boot()
    {
        parent::boot();
        
        static::addGlobalScope('owned', function (Builder $builder) {
            if (Auth::check() && !empty(Auth::user()->tv_id)) {
                $builder->where('media_streams.tv_id', Auth::user()->tv_id);
            }
        });

        static::saving(function ($instance){
            if (Auth::check() && !empty(Auth::user()->tv_id)) {
                $instance->tv_id = Auth::user()->tv_id;
            }
        });
    }

    public function tv()
    {
        return $this->belongsTo('App\TV');
    }
}

app/Http/Controllers/Admin/MediaStreamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\CreateMediaStreamRequest;
use App\Http\Requests\UpdateMediaStreamRequest;
use App\Repositories\MediaStreamRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MediaStreamController extends AppBaseController
{
    /** @var  MediaStreamRepository */
    private $mediaStreamRepository;

    public function __construct(MediaStreamRepository $mediaStreamRepo)
    {
        $this->mediaStreamRepository = $mediaStreamRepo;
    }

    /**
     * Display a listing of the MediaStream.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $mediaStreams = $this->mediaStreamRepository->allQuery()->with('tv')->paginate(10);

        return view('admin.media_streams.index')
            ->with('mediaStreams', $mediaStreams);
    }

    /**
     * Show the form for creating a new MediaStream.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.media_streams.create');
    }

    /**
     * Store a newly created MediaStream in storage.
     *
     * @param CreateMediaStreamRequest $request
     *
     * @return Response
     */
    public function store(CreateMediaStreamRequest $request)
    {
        $input = $request->all();

        $mediaStream = $this->mediaStreamRepository->create($input);

        Flash::success('Media Stream saved successfully.');

        return redirect(route('admin.mediaStreams.index'));
    }

    /**
     * Display the specified MediaStream.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $mediaStream = $this->mediaStreamRepository->find($id);

        if (empty($mediaStream)) {
            Flash::error('Media Stream not found');

            return redirect(route('admin.mediaStreams.index'));
        }

        return view('admin.media_streams.show')->with('mediaStream', $mediaStream);
    }

    /**
     * Show the form for editing the specified MediaStream.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $mediaStream = $this->mediaStreamRepository->find($id);

        if (empty($mediaStream)) {
            Flash::error('Media Stream not found');

            return redirect(route('admin.mediaStreams.index'));
        }

        return view('admin.media_streams.edit')->with('mediaStream', $mediaStream);
    }

    /**
     * Update the specified MediaStream in storage.
     *
     * @param int $id
     * @param UpdateMediaStreamRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMediaStreamRequest $request)
    {
        $mediaStream = $this->mediaStreamRepository->find($id);

        if (empty($mediaStream)) {
            Flash::error('Media Stream not found');

            return redirect(route('admin.mediaStreams.index'));
        }

        $mediaStream = $this->mediaStreamRepository->update($request->all(), $id);

        Flash::success('Media Stream updated successfully.');

        return redirect(route('admin.mediaStreams.index'));
    }

    /**
     * Remove the specified MediaStream from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $mediaStream = $this->mediaStreamRepository->find($id);

        if (empty($mediaStream)) {
            Flash::error('Media Stream not found');

            return redirect(route('admin.mediaStreams.index'));
        }

        $this->mediaStreamRepository->delete($id);

        Flash::success('Media Stream deleted successfully.');

        return redirect(route('admin.mediaStreams.index'));
    }
}

resources/views/admin/media_streams/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Media Stream
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.mediaStreams.store']) !!}

                        @include('admin.media_streams.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/media_streams/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Media Stream
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($mediaStream, ['route' => ['admin.mediaStreams.update', $mediaStream->id], 'method' => 'patch']) !!}

                        @include('admin.media_streams.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/media_streams/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Tv Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('tv_id', 'TV:') !!}
    {!! Form::select('tv_id', \App\TV::pluck('name','id'), null, ['required' => true, 'placeholder' => 'Choose', 'class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('admin.mediaStreams.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/media_streams/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Media Streams</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('admin.mediaStreams.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.media_streams.table')
            </div>
        </div>
        <div class="text-center">
        
        @include('adminlte-templates::common.paginate', ['records' => $mediaStreams])

        </div>
    </div>
@endsection

resources/views/admin/media_streams/table.blade.php
<div class="table-responsive">
    <table class="table" id="mediaStreams-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>TV</th>
                <th>Created At</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($mediaStreams as $mediaStream)
            <tr>
                <td>{!! $mediaStream->name !!}</td>
                <td>{!! $mediaStream->tv->name !!}</td>
                <td>{!! $mediaStream->created_at !!}</td>
                <td>
                    {!! Form::open(['route' => ['admin.mediaStreams.destroy', $mediaStream->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{!! route('admin.mediaStreams.edit', [$mediaStream->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>